"use client";
import { useEffect } from "react";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FlipNav } from "@/components/nav-bar/NavBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function useCustomCursor() {
  useEffect(() => {
    const handleMouseDown = () => {
      document.body.classList.add("red-cursor");
    };

    const handleMouseUp = () => {
      document.body.classList.remove("red-cursor");
    };

    document.addEventListener("mousedown", handleMouseDown);
    document.addEventListener("mouseup", handleMouseUp);

    // Cleanup event listeners on component unmount
    return () => {
      document.removeEventListener("mousedown", handleMouseDown);
      document.removeEventListener("mouseup", handleMouseUp);
    };
  }, []);
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useCustomCursor();

  return (
    <html lang="en" className="h-screen">
      <body
        className={`relative min-h-screen bg-green-200 flex flex-col justify-start items-center border ${inter.className}`}
      >
        <FlipNav />
        <div className="flex flex-col max-w-4xl">{children}</div>
      </body>
    </html>
  );
}
